### ISSUE TITLE
Hello author, I have some questions that I would like to consult with

### ISSUE THREAD

**Issue by Yinter-ai** [spear-sim/spear#301]
Hello author, I have a few questions to consult. The first question is if I want to use the v0.5.0 version you provided to implement interoperability with the MuJoCo physics engine, which is the case example/mujoco-inlterop. Can I not build my own spear sim and just use the compiled version you provided to implement it? The second question is if I don't want to build spear sim on my own computer and only want to use the pre compiled version of v0.5.0 you provided to create an object in the scene, how should I operate? The last question is: First, I want to ask what are the differences between the pre compiled version you provided and the spear sim we built ourselves from source code? What's the difference? If I build this spear sim generated from source code compilation on my computer, So can I directly transplant the compiled and generated version to another computer to achieve the same functionality

**Comment by mikeroberts3000** [comment]
> _The first question is if I want to use the v0.5.0 version you provided to implement interoperability with the MuJoCo physics engine, which is the case example/mujoco-inlterop. Can I not build my own spear sim and just use the compiled version you provided to implement it?_

I'm not sure I understand your question because of how it is worded. If you are primarily interested in the MuJoCo interop example, you should be able to work with the `0.5.0` code. A precompiled `0.5.0` executable should work, and building your own executable should work too. If you're using an `0.5.0` executable (precompiled or not), just make sure to roll back all the code in your local repository to the `0.5.0` release tag, because the Python code you're using (i.e., everything in the `spear` Python module) needs to match the executable you're using. To get the MuJoCo interop example working, you'll need to run our export pipeline, so follow our documentation that explains how to do that. To run our export pipeline, you'll need to install Unreal 5.2. If you can spare the hard drive space, I recommend also keeping Unreal 5.5 around, because I'm planning to fix the Windows build ASAP. As soon as the Windows build is working again, it will be much easier to do everything you want to do (e.g., MuJoCo interop, spawning objects) if you're running our latest code on Unreal 5.5.

(Sorry for the delay. I just changed jobs and I don't have a working Windows computer right now. The current status is that I'm waiting for my Windows machine to be delivered. It is scheduled for delivery next Friday.)

> _The second question is if I don't want to build spear sim on my own computer and only want to use the pre compiled version of v0.5.0 you provided to create an object in the scene, how should I operate?_

It has become significantly easier to spawn your own custom objects after the `0.5.0` release. If you are interested in this functionality, the easiest way forward will be to build your own executable. If you don't want to wait until I have a chance to fix the Windows build, a straightforward workaround would be to find a commit where the `import_stanford_dataset` example has already been implemented, but before we updated to Unreal 5.4. For example, try the commit in `main` on October 17 of this year. That was the last commit where we were still using Unreal 5.2, so I think it will build correctly on Windows. If you start experimenting with this slightly older version of the code, everything you learn, and 99% of the code you write will transfer over to the latest version of the code perfectly, so don't worry about wasting effort.

> _The last question is: First, I want to ask what are the differences between the pre compiled version you provided and the spear sim we built ourselves from source code? What's the difference? If I build this spear sim generated from source code compilation on my computer, So can I directly transplant the compiled and generated version to another computer to achieve the same functionality_

There is no difference. If you sync to the `0.5.0` release tag and build a `Shipping` executable, the executable you get will match our precompiled `0.5.0` executable exactly. The executable you get might not be bitwise-identical to ours, e.g., if you have a slightly different version of Windows or Visual Studio etc, but it will be functionally equivalent. You can inspect the exact script that we use to build our precompiled executables at `tools/build_executable.py`. In this script, you can verify for yourself that there are no magic hidden steps or extra code changes going on.
